[build-system]
requires = ["setuptools>=67"]
build-backend = "setuptools.build_meta"

[project]
name = "set-iptables"
dynamic = ["version"]
description = "Arch Linux installer - guided, templates etc."
authors = [
    {name = "Giuliano Vallone", email = "glnvlln0@gmail.com"},
]
readme = "README.md"
requires-python = ">=3.10"

keywords = ["linux", "iptables", "set-iptables", "installer"]

classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: POSIX :: Linux",
]

[project.urls]
Home = "https://github.com/Iaio99/set-iptables"
#Documentation = "https://set-iptables.readthedocs.io/"
Source = "https://github.com/Iaio99/set-iptables"

[project.scripts]
set-iptables = "set-iptables:main"

[project.optional-dependencies]
doc = ["sphinx"]

[tool.mypy]
python_version = "3.10"
exclude = "tests"

[tool.bandit]
targets = ["set-iptables"]
exclude = ["/tests"]